---
output: html_document
---

## International LPI
The [Logistics Performance Index (LPI)](http://lpi.worldbank.org/) is a benchmarking tool created to assess and compare the performance of 160 countries on trade logistics.  The LPI is based on a worldwide survey of operators on the ground (global freight forwarders and express carriers), providing feedback on the logistics “friendliness” of the countries in which they operate and those with which they trade. They combine in-depth knowledge of the countries in which they operate with informed qualitative assessments of other countries where they trade and experience of global logistics environment. Feedback from operators is supplemented with quantitative data on the performance of key components of the logistics chain in the country of work.

The LPI consists therefore of both qualitative and quantitative measures and helps build profiles of logistics friendliness for these countries. It measures performance along the logistics supply chain within a country and offers two different perspectives: international and domestic. The information presented in this project focuses only on the international perspective.

The international IPL provides qualitative evaluations of a country in six areas by its trading partners—logistics professionals working outside the country. The components analyzed in the International LPI were chosen based on recent theoretical and empirical research and on the practical experience of logistics professionals involved in international freight forwarding. They are:

- The efficiency of customs and border management clearance ("Customs")
- The quality of trade and transport infrastructure ("Infrastructure")
- The ease of arranging competitively priced shipments ("Ease of arranging shipments")
- The competence and quality of logistics services—trucking, forwarding, and customs brokerage ("Quality of logistics services")"
- The ability to track and trace consignments ("Tracking and tracing")
- The frequency with which shipments reach consignees within scheduled or expected delivery times ("Timeliness")

The LPI uses standard statistical techniques to aggregate the data into a single indicator that can be used for cross-country comparisons. You can find more information regarding the LPI methodology [here](https://wb-lpi-media.s3.amazonaws.com/LPI%20Methodology.pdf").

## Colophon
This app was made by [Brad Boehmke](http://bradleyboehmke.github.io/) using [Shiny](http://shiny.rstudio.com/) and [RMarkdown](http://rmarkdown.rstudio.com/) provided by [RStudio](https://www.rstudio.com/). Code is available on [GitHub](https://github.com/bradleyboehmke), licensed MIT. Suggestions and criticism welcome: [bradleyboehmke@gmail.com](mailto:bradleyboehmke.com).
